version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "type: dependencies"
      - "area: infra"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    cooldown:
      default-days: 5
    labels:
      - "type: dependencies"
    groups:
      patch-and-minor:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
      day: "monday"
    cooldown:
      default-days: 8
    labels:
      - "type: dependencies"
      - "area: infra"
