export enum Permission {
  Admin = 'admin',
  BoardViewer = 'board-viewer',
  BoardUploader = 'board-uploader',
  BoardValidator = 'board-validator',
  TerritoriesViewer = 'territories-viewer',
  TerritoriesManager = 'territories-manager',
  ProspectionViewer = 'prospection-viewer',
  ProspectionManager = 'prospection-manager',
  SettingsUserManager = 'settings-user-manager',
  PublisherViewer = 'publisher-viewer',
  PublisherManager = 'publisher-manager',
  ActivityViewer = 'activity-viewer',
  ActivityManager = 'activity-manager',
  ProgramViewer = 'program-viewer',
  ProgramManager = 'program-manager',
  ExternalSpeakerViewer = 'external-speaker-viewer',
  ExternalSpeakerManager = 'external-speaker-manager',
  RolesViewer = 'roles-viewer',
  RolesManager = 'roles-manager',
  PermissionsManager = 'permissions-manager',
}
