-- CreateEnum
CREATE TYPE "PublisherType" AS ENUM ('normal', 'pionnier-auxiliaires', 'pionnier-permanant', 'pionnier-special', 'missionnaire');

-- CreateEnum
CREATE TYPE "TerritoryKind" AS ENUM ('doors-to-doors', 'campus', 'commerces', 'phones', 'hotel');

-- CreateEnum
CREATE TYPE "EntranceKind" AS ENUM ('residential', 'commerce', 'hotel', 'laundromat', 'campus');

-- CreateEnum
CREATE TYPE "TerritoryAttributionKind" AS ENUM ('default', 'phones', 'campaign');

-- AlterTable User.type String → PublisherType (preserves existing data via USING)
ALTER TABLE "User" ALTER COLUMN "type" DROP DEFAULT;
ALTER TABLE "User" ALTER COLUMN "type" TYPE "PublisherType" USING "type"::"PublisherType";
ALTER TABLE "User" ALTER COLUMN "type" SET DEFAULT 'normal'::"PublisherType";

-- AlterTable Territory.type String → TerritoryKind
ALTER TABLE "Territory" ALTER COLUMN "type" DROP DEFAULT;
ALTER TABLE "Territory" ALTER COLUMN "type" TYPE "TerritoryKind" USING "type"::"TerritoryKind";
ALTER TABLE "Territory" ALTER COLUMN "type" SET DEFAULT 'doors-to-doors'::"TerritoryKind";

-- AlterTable Attribution.type String → TerritoryAttributionKind
ALTER TABLE "Attribution" ALTER COLUMN "type" DROP DEFAULT;
ALTER TABLE "Attribution" ALTER COLUMN "type" TYPE "TerritoryAttributionKind" USING "type"::"TerritoryAttributionKind";
ALTER TABLE "Attribution" ALTER COLUMN "type" SET DEFAULT 'default'::"TerritoryAttributionKind";

-- AlterTable BuildingEntrance.kind String → EntranceKind
ALTER TABLE "BuildingEntrance" ALTER COLUMN "kind" DROP DEFAULT;
ALTER TABLE "BuildingEntrance" ALTER COLUMN "kind" TYPE "EntranceKind" USING "kind"::"EntranceKind";
ALTER TABLE "BuildingEntrance" ALTER COLUMN "kind" SET DEFAULT 'residential'::"EntranceKind";

-- AlterTable PublisherActivity.type String → PublisherType
ALTER TABLE "PublisherActivity" ALTER COLUMN "type" DROP DEFAULT;
ALTER TABLE "PublisherActivity" ALTER COLUMN "type" TYPE "PublisherType" USING "type"::"PublisherType";
ALTER TABLE "PublisherActivity" ALTER COLUMN "type" SET DEFAULT 'normal'::"PublisherType";

-- DropIndex (generated by prisma migrate diff — index was renamed upstream)
DROP INDEX IF EXISTS "BoardDynamicDocumentSettings_congregationId_dynamicType_dyn_key";

-- RenameIndex
ALTER INDEX IF EXISTS "NotificationPreference_userId_notificationType_congregationId_k" RENAME TO "NotificationPreference_userId_notificationType_congregation_key";
