import type { TransactionClient } from '~/shared/infra/db.server'
import logger from '~/shared/infra/logger.server'
import { deleteFile } from './document.server'
import { deleteBoardFile } from './document-storage.server'
import { thumbnailQueue } from './thumbnail-queue.server'

/**
 * Records a new version row representing the file just uploaded. Each version
 * row mirrors the document state at upload time, so the latest row always
 * matches the current `BoardDocument.uri`. Ownership and history both rely on
 * this invariant.
 */
export async function createVersionForUpload(
  db: TransactionClient,
  documentId: number,
  congregationId: number,
  uploadedById: number,
  uri: string,
  thumbnailUri: string | null = null,
): Promise<void> {
  const lastVersion = await db.boardDocumentVersion.findFirst({
    where: { documentId },
    orderBy: { versionNumber: 'desc' },
    select: { versionNumber: true },
  })

  await db.boardDocumentVersion.create({
    data: {
      documentId,
      uri,
      thumbnailUri,
      versionNumber: (lastVersion?.versionNumber ?? 0) + 1,
      uploadedById,
      congregationId,
    },
  })
}

/**
 * Restaure une version anterieure du document.
 * Sauvegarde la version courante, remplace le fichier, et relance la generation de la miniature.
 */
export async function restoreDocumentVersion(
  db: TransactionClient,
  documentId: number,
  versionId: number,
  congregationId: number,
  uploadedById: number,
): Promise<{ versionNumber: number } | null> {
  const version = await db.boardDocumentVersion.findUnique({
    where: {
      id_congregationId: { id: versionId, congregationId },
    },
  })

  if (version == null || version.documentId !== documentId) {
    return null
  }

  const currentDoc = await db.boardDocument.findUnique({
    where: {
      id_congregationId: { id: documentId, congregationId },
    },
    select: { uri: true, thumbnailUri: true },
  })

  // Restore is recorded as a fresh version pointing at the restored uri so the
  // latest row continues to match the current BoardDocument.uri.
  await createVersionForUpload(db, documentId, congregationId, uploadedById, version.uri)

  // Restore: update URI, clear thumbnail (will be regenerated by worker)
  await db.boardDocument.update({
    where: {
      id_congregationId: { id: documentId, congregationId },
    },
    data: {
      uri: version.uri,
      thumbnailUri: null,
    },
  })

  // Clean up old thumbnail if it was replaced
  if (currentDoc?.thumbnailUri) {
    await deleteFile({ uri: currentDoc.thumbnailUri })
  }

  // Enqueue thumbnail regeneration from the restored file
  await thumbnailQueue.add('generate-thumbnail', {
    congregationId,
    documentId,
    pdfStorageKey: version.uri,
  })

  return { versionNumber: version.versionNumber }
}

/**
 * Supprime tous les fichiers stockes des versions d'un document.
 * Les lignes en base sont supprimees par ON DELETE CASCADE.
 */
export async function deleteAllVersionFiles(db: TransactionClient, documentId: number): Promise<void> {
  const versions = await db.boardDocumentVersion.findMany({
    where: { documentId },
    select: { uri: true, thumbnailUri: true },
  })

  for (const version of versions) {
    try {
      await deleteBoardFile(version.uri)
    } catch (error) {
      logger.error(`Failed to delete version file: ${version.uri}`, { error })
    }
    if (version.thumbnailUri) {
      try {
        await deleteBoardFile(version.thumbnailUri)
      } catch (error) {
        logger.error(`Failed to delete version thumbnail: ${version.thumbnailUri}`, { error })
      }
    }
  }
}
